### ISSUE TITLE
receive notifications for proposals

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrlibwallet#151]
We need the client to send out notifications for certain events regarding politeia.

These events are listed below;

1. A notification should be broadcast when there is a new proposal
2. A notification should be broadcast when a vote for a proposal has started
3. A notification should be broadcast when a vote for a proposal has ended 

The preferred response type for this function should be a callback response

**Comment by C-ollins** [comment]
There's currently no way to subscribe to proposal notifications, what you can do is call a function to check for new proposals or any other action.

**Comment by dreacot** [comment]
Okay noted

**Comment by C-ollins** [comment]
Closed by #170
