### ISSUE TITLE
fetch vote result of proposals

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrlibwallet#159]
A function for fetching;

1. Vote results for all fetched proposals from #153 
A reference to the Api docs can be found here: https://github.com/decred/politeia/blob/master/politeiawww/api/www/v1/api.md#proposal-vote-status

2. Vote results for individual proposals using the censorship token 
A reference to the Api docs can be found here: https://github.com/decred/politeia/blob/master/politeiawww/api/www/v1/api.md#proposals-vote-status

Preferred response type would be a blocking response

**Comment by C-ollins** [comment]
Closed by #170
