### ISSUE TITLE
VSPD: error on paying ticket fees

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/dcrlibwallet#176]
I get this error occasionally when tyring to pay a ticket fee. [PayVSPFee] err: failed to get votingKeyWIF for TsVVas5a18YE3CkWV1HFN81zwQ2Z2QFNbSP: wallet.DumpWIFPrivateKey:: wallet.LoadPrivateKey: no private key for default/1/123 
This seems to be as a result of the wallet getting locked just before attempting to pay a fee.

**Comment by raedah** [comment]
https://github.com/oshorefueled/dcrlibwallet/tree/ticket-fee

**Comment by oshorefueled** [comment]
#189 resolves this issue
